### ISSUE TITLE
Deploy MTA - Host is taken

### ISSUE THREAD

**Issue by vishalkr31** [jacobahtan/bootcamp-cap-bookshop#1]
While deploying the .mtar file to CF , I am getting below error : 
Error creating or updating application "bookshop-srv": Controller operation failed: 400 Bad Request: CF-RouteHostTaken(210003): The host is taken: bookcatalog-bootcamp

[bookshop deploy error.docx](https://github.com/jacobahtan/bootcamp-cap-bookshop/files/6850058/bookshop.deploy.error.docx)

**Comment by jacobahtan** [comment]
In the mta.yaml file, there's a parameter of appname which you could define a unique route name for your entire app to be deployed in BTP. 

Fix: replace bookcatalog-bootcamp with another unique name (e.g. bookcatalog-vishal), so that it doesn't exist in the trial domain. 

Screenshot example
![image](https://user-images.githubusercontent.com/8436161/126374609-09a014ad-e647-41f8-97e7-e3dda46ccc60.png)

**Comment by jacobahtan** [comment]
> While deploying the .mtar file to CF , I am getting below error : 
> 
> Error creating or updating application "bookshop-srv": Controller operation failed: 400 Bad Request: CF-RouteHostTaken(210003): The host is taken: bookcatalog-bootcamp
> 
> 
> 
> 
> 
> [bookshop deploy error.docx](https://github.com/jacobahtan/bootcamp-cap-bookshop/files/6850058/bookshop.deploy.error.docx)
> 
> 
> 
> 

Refer to fix above.

**Comment by jacobahtan** [comment]
> While deploying the .mtar file to CF , I am getting below error : 
> 
> Error creating or updating application "bookshop-srv": Controller operation failed: 400 Bad Request: CF-RouteHostTaken(210003): The host is taken: bookcatalog-bootcamp
> 
> 
> 
> 
> 
> [bookshop deploy error.docx](https://github.com/jacobahtan/bootcamp-cap-bookshop/files/6850058/bookshop.deploy.error.docx)
> 
> 
> 
> 

In the mta.yaml file, there's a parameter of appname which you could define a unique route name for your entire app to be deployed in BTP.

Fix: replace bookcatalog-bootcamp with another unique name (e.g. bookcatalog-vishal), so that it doesn't exist in the trial domain.

Screenshot example
![image](https://user-images.githubusercontent.com/8436161/126374761-ace9f5a4-aee1-4aeb-befc-9c22b0d32dc3.png)

**Comment by vishalkr31** [comment]
Thanks Jacob,
I am able to deploy the app , But
the service - bookshop-db-deployer is getting Crashed , details in attachment.
while the service - bookshop-srv is fine.
[bookshop2.docx](https://github.com/jacobahtan/bootcamp-cap-bookshop/files/6853364/bookshop2.docx)

**Comment by jacobahtan** [comment]
> Thanks Jacob,
> I am able to deploy the app , But
> the service - bookshop-db-deployer is getting Crashed , details in attachment.
> while the service - bookshop-srv is fine.
> [bookshop2.docx](https://github.com/jacobahtan/bootcamp-cap-bookshop/files/6853364/bookshop2.docx)

Hi Vishal. It's fine. The role of the db-deployer is to push the HANA artefacts into BTP.
Thus, once it has done & completed, you can disregard db-deployer. 
In most cases, I'd advise to delete the service away manually from your list of applications in your BTP account so to free up more routes in your trial.

To ensure completeness & full deployment. You may check the following:
- open SAP HANA Cloud > HANA DB Explorer > check that bookshop data is loaded.
- open bookshop-srv app > ensure endpoints are accessible.
- SAP BTP Cockpit > HTML5 Applications: check that the Fiori application is running fine. (If you don't see this, create a service instance of SAP Launchpad).

**Comment by vishalkr31** [comment]
Hi , out of 3 , only 2nd is working , while 1st and 3rd are not
screen shots attached.
[bookshop3.docx](https://github.com/jacobahtan/bootcamp-cap-bookshop/files/6853599/bookshop3.docx)

**Comment by jacobahtan** [comment]
> Hi , out of 3 , only 2nd is working , while 1st and 3rd are not
> screen shots attached.
> [bookshop3.docx](https://github.com/jacobahtan/bootcamp-cap-bookshop/files/6853599/bookshop3.docx)

**Moving forward, please create an issue over our MS Teams channel for the bootcamp.**

1. DB Explorer > Tables (not query.sql) > Open Books Table > See if records are there or not.
2. Good.
3. I need more log from this.
